version: '3'

services:

  # redis:
  #   restart: always
  #   container_name: flatter-redis
  #   image: redis:alpine
  #   command: redis-server --appendonly yes
  #   volumes:
  #     - redis-data:/data
  #   expose:
  #     - 6379
  #   networks:
  #     - frontend

  frontend:
    restart: always
    container_name: frontend
    image: frontend:latest
    build: 
      context: .
      dockerfile: client/docker/Dockerfile
      # args:
      #   API_SERVER: ${API_SERVER_URL}
    # environment:
    #   NODE_ENV: ${NODE_ENV}
    #   REACT_APP_PAYPAL_CLIENT_ID: ${REACT_APP_PAYPAL_CLIENT_ID}
    command: sh -c "serve -s build -l 3000 --no-clipboard"
    expose:
      - 3000
    networks:
      - frontend

  nginx:
    restart: always
    container_name: frontend-nginx
    image: frontend-nginx:latest
    build:
        context: ./nginx
        dockerfile: ./Dockerfile
    # volumes:
    #   - static:/usr/src/app/flatter-backend/static
    #   - static:/usr/src/app/flatter-backend/media
    ports:
      - 80:80
    depends_on:
      - frontend
    networks:
      - frontend

# volumes:
#   static:
#     name: flatter-static
#   redis-data:
#     name: flatter-redis-data


networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16